s3.1 typo correction
tlswg/tls-subcerts pull request #88
Opened 2021-08-28 01:21 UTC by seanturner

2021-08-28 01:27 UTC, seanturner commented
Addresses #89.

2021-08-31 22:27 UTC, grittygrease requested changes
Remove repeated sentence.

2021-08-31 22:27 UTC, grittygrease commented on draft-ietf-tls-subcerts.md
> +  This prevents them from being used with other, perhaps unintended signature
Repeated sentence

2021-08-31 22:34 UTC, grittygrease requested changes

2021-08-31 22:34 UTC, grittygrease commented on draft-ietf-tls-subcerts.md
> +  the one in the servers certificate can be different.
This applies to more than just server certificates. Maybe say:
"The signature algorithm bound to the delegated credential can be chosen independently of the set of signature algorithms supported by the end-entity certificate."

2021-09-07 16:22 UTC, jsalowey approved these changes

2021-09-14 15:10 UTC, chris-wood approved these changes

2021-09-14 15:11 UTC, merged